export const FETCH_USER = 'FETCH_USER';
export const CREATE_USER = 'CREATE_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const USER_CREATED = 'USER_CREATED';
export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_DELETED = 'USER_DELETED';

export const FETCH_GOODS = 'FETCH_GOODS';
export const GOODS_RECEIVED = 'GOODS_RECEIVED';
export const CREATE_GOODS_ITEM = 'CREATE_GOODS_ITEM';
export const RECEIVE_GOODS_ITEM = 'RECEIVE_GOODS_ITEM';
export const UPDATE_GOODS_ITEM = 'UPDATE_GOODS_ITEM';
export const DELETE_GOODS_ITEM = 'DELETE_GOODS_ITEM';

export const GOODS_ITEM_CREATED = 'GOODS_ITEM_CREATED';
export const GOODS_ITEM_RECEIVED = 'GOODS_ITEM_RECEIVED';
export const GOODS_ITEM_UPDATED = 'GOODS_ITEM_UPDATED';
export const GOODS_ITEM_DELETED = 'GOODS_ITEM_DELETED';
